### ISSUE TITLE
Potential Data Race

### ISSUE THREAD

**Issue by mert-kurttutan** [Narsil/ggblas#1]
Hi,
I think there is possibly data race in the function `ggml_compute_forward_mul_mat`.

From my understanding, the problem is that we are mutating c matrix, `cp`. But there is a possibility of different threads mutating the same memory inside c matrix. This occurs when `totalth < n`, inside the function `gml_compute_forward_mul_mat`. Here, `totalth` refers to displacement length for memory address between consecutive thread execution and `n` is the length of array mutated inside c matrix.

I have to run `cargo test` multiple time due to stochastic nature of thread execution. After a few trial, I get the following
```
running 3 tests
test tests::ggml_simple_t ... ok
test tests::ggml_simple2 ... ok
test tests::ggml_simple ... FAILED

failures:

---- tests::ggml_simple stdout ----
thread 'tests::ggml_simple' panicked at 'assertion failed: `(left == right)`
  left: `[50.0, 60.0, 114.0, 140.0, 178.0, 202.0]`,
 right: `[50.0, 60.0, 114.0, 140.0, 178.0, 220.0]`', src/lib.rs:461:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::ggml_simple

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

```

For modals like llama, and whisper, this does not really matter since all I used (in my case), was matmul_transposed.

I was thinking of a way to fix this without performance sacrifice. Maybe, microkernel could be used, but this is already implemented `matrixmultiply` crate ??

**Comment by mert-kurttutan** [comment]
FYI, when I limited the total thread number to 1,2, it works without any error.

**Comment by mert-kurttutan** [comment]
Just to be precise, to get rid of this matmul problem, I had to change  ctx.v tensor to ctx.v_t and some other operation for attention layer

**Comment by Narsil** [comment]
@mert-kurttutan 

Can you provide more information about your environemnet ? I ran 1000 times those tests without any issues.
Or something you use to reproduce ? 

Here running on Linux + 8 threads (4 physical).

There definitely could be a threading issue since  this particular op is accumulating results, but the frequency should be rather low.

**Comment by mert-kurttutan** [comment]
I can reproduce the error by cloning the repo and running `cargo test` multiple times (until the error).
For my ubuntu machine,  see system info below, no change is needed to reproduce the error.

But for my mac m1 machine, there is a missing piece of code in `src/ggml/mod.rs` to declare neon module and CurrentCPu, see blow

```rust
#[cfg(any(target_arch = "arm", target_arch = "aarch64"))]
#[cfg(target_feature = "neon")]
pub mod neon;
#[cfg(any(target_arch = "arm", target_arch = "aarch64"))]
#[cfg(target_feature = "neon")]
pub use neon::CurrentCpu;
```
Other than this code, no change is done to reproduce the error on my m1 machine.



Linux machine: 
```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  12
  On-line CPU(s) list:   0-11
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz
    CPU family:          6
    Model:               165
    Thread(s) per core:  2
    Core(s) per socket:  6
    Socket(s):           1
    Stepping:            2
    CPU max MHz:         4500.0000
    CPU min MHz:         800.0000
    BogoMIPS:            4999.90

```

Mac OS M1 Machine:

```
Software:
    System Software Overview:

      System Version: macOS 12.6.2 (21G320)
      Kernel Version: Darwin 21.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: mert’s MacBook Pro
      User Name: mert kurttutan (mertkurttutan)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 3 days 18:43

Hardware:
    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro17,1
      Chip: Apple M1
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 7459.141.1
      OS Loader Version: 7459.141.1
      Serial Number (system): FVFGD009Q05P
      Hardware UUID: C74150FE-D0C3-52BA-809B-4A24939D804A
      Provisioning UDID: 00008103-001611A93488801E
      Activation Lock Status: Disabled

```

**Comment by Narsil** [comment]
Interesting, I'm really unable to reproduce on Linux, but I can indeed on M1 too.

But the bug triggers less in release (probably shorter operations).
I'm still confused as to why it's not triggered on my Linux. (We definitely don't want Mutex if we can avoid it here).

**Comment by mert-kurttutan** [comment]
I think it might be related to the number of threads available. The more number of threads available, the more likely it is for consecutive thread execution to intersection in memory, since this condition `totalth < n` I mentioned in my first message. Maybe if you try linux machine with higher number of threads, it should be more likely. For instance my machine was able to achieve around peak 800-900 %cpu utilization.

Edit: 800-900% cpu utilization was achieved with test that has much bigger matrices

**Comment by Narsil** [comment]
Ok, I should have fixed by assigning C rows to each threads. This slows down the thing a bit.

Actually for mat mul n , https://github.com/sarah-ek/gemm this crate is faster.

I haven't had time yet to dig into it and take the best of it in order to get the good performance. matmul t performance on this wasn' t great
